# Cloud Build Configuration for Homelab ISO Builder
# Automatically build and deploy on push to main branch

steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']
    dir: 'webapp/backend'

  # Run tests (if available)
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['test']
    dir: 'webapp/backend'
    env:
      - 'NODE_ENV=test'

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/homelab-iso-builder:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/homelab-iso-builder:latest'
      - '-f'
      - 'webapp/deployment/Dockerfile'
      - '.'

  # Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/homelab-iso-builder:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/homelab-iso-builder:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'homelab-iso-builder'
      - '--image=gcr.io/$PROJECT_ID/homelab-iso-builder:$COMMIT_SHA'
      - '--region=us-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production,GCP_PROJECT_ID=$PROJECT_ID'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/homelab-iso-builder:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/homelab-iso-builder:latest'

# Build timeout
timeout: 1200s

options:
  machineType: 'N1_HIGHCPU_8'
